### ISSUE TITLE
Can't run main.py - txdbus.error.RemoteError: org.bluez.Error.InProgress: Operation already in progress

### ISSUE THREAD

**Issue by comfy332** [delphiki/AirStatus#1]
Running `main.py` produces the following error:
```
Traceback (most recent call last):
  File "/home/user/AirStatus/main.py", line 110, in <module>
    run()
  File "/home/user/AirStatus/main.py", line 96, in run
    data = get_data()
  File "/home/user/AirStatus/main.py", line 38, in get_data
    raw = get_data_hex()
  File "/home/user/AirStatus/main.py", line 31, in get_data_hex
    a = loop.run_until_complete(get_device())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/AirStatus/main.py", line 15, in get_device
    devices = await discover()
  File "/home/user/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/discovery.py", line 188, in discover
    await bus.callRemote(
txdbus.error.RemoteError: org.bluez.Error.InProgress: Operation already in progress
```

I have connected my Airpods to the device and it works fine, with audio playing and everything.
The only change I have made is that I installed Pillow version 8.0.0 over 7.2.0 to get it to work with Python 3.9.

Some help would be appreciated, thanks.

**Comment by d-knafo** [comment]
Any solution ?

**Comment by melvinroest** [comment]
I've got the same issue here.

**Comment by delphiki** [comment]
Did you change back the bluetooth controller mode to "dual" after pairing your airpods?

**Comment by dannyk81** [comment]
> Did you change back the bluetooth controller mode to "dual" after pairing your airpods?

could you elaborate on this? or how one would change/check the mode?

**Comment by delphiki** [comment]
> could you elaborate on this? or how one would change/check the mode?

Check in the file /etc/bluetooth/main.conf that the ControllerMode is set to dual:
```
ControllerMode = dual
```
If not, change it, and restart the bluetooth service: `sudo systemctl restart bluetooth`

**Comment by dannyk81** [comment]
> > could you elaborate on this? or how one would change/check the mode?
> 
> Check in the file /etc/bluetooth/main.conf that the ControllerMode is set to dual:
> 
> ```
> ControllerMode = dual
> ```
> 
> If not, change it, and restart the bluetooth service: `sudo systemctl restart bluetooth`

That did it! thanks 😄

**Comment by enx1998** [comment]
Hi @delphiki, I have the same error and I have the bluethoot mode "dual" active. The difference is that I have two bluethoot adapters in use at the same time. Is it possible that my configuration is causing the issue?

Thanks, ENx
