### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by treibholz** [delphiki/AirStatus#5]
Hi,
please consider adding a license to this project, so contributions and/or forks are legally save.

I'm really happy and thankful, that I found this project! It is the first one, that makes it possible to get the status of my Airpods in a sane way on Linux and I would love to help improve it (and/or use the code in module for [Py3status](https://py3status.readthedocs.io/en/latest/)).

According to your README.md, you (or the inactive parent of your fork) took some code from https://github.com/ohanedan/Airpods-Windows-Service, which is licensed under GPL-3.0.
I assume, this means that your code must also be licensed under GPL-3.0 and you would also need to add the LICENCE file.

**Comment by delphiki** [comment]
Thanks for the heads up, license added :ok_hand:
